/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as baseSol from "./Base.sol";
export type { baseSol };
import type * as safe2LinkPluginSol from "./Safe2LinkPlugin.sol";
export type { safe2LinkPluginSol };
import type * as test from "./test";
export type { test };
